---
- name: Mattermost
  hosts: all
  become: yes
  tags:
    - mattermost
  vars:
    - domain: "mattermost.{{ root_domain }}"
    - certbot_email: soc-srcf-admin@lists.cam.ac.uk
    - mattermost_version: 5.37.1
    - mattermost_checksum: sha256:a70e829180ed5d3b3e688f1d264bafae93a7ecf80970e16b673c5473beaf137f  -
    - mattermost_admin_password_path: /root/mattermost-admin-password
    - mattermost_public_link_salt_path: /root/mattermost-public-link-salt

  roles:
    - certbot
    - mattermost

- name: Matrix bridges
  hosts: all
  become: yes
  tags:
    - matrix
  vars:
    - domain: "matrix.{{ root_domain }}"
    - matrix_server_name: "{{ root_domain }}"
    - certbot_email: soc-srcf-admin@lists.cam.ac.uk
    - ubuntu_version: focal
    - keyring_location: /usr/share/keyrings/matrix-org-archive-keyring.gpg
    - matrix_irc_port: 9999
    - matrix_mattermost_port: 9998
    - matrix_mattermost_webhook_port: 9898
    - mattermost_matrixbot_password_path: /root/mattermost-matrixbot-password
    - mattermost_matrixbot_token_path: /root/mattermost-matrixbot-token
    - matrix_irc_bridges:
       - { irc: "#general", matrix: "general" }
       - { irc: "#hackday", matrix: "hackday" }
       - { irc: "#welcome", matrix: "welcome" }
       - { irc: "#society", matrix: "society" }
       - { irc: "#executive", matrix: "executive" }
       - { irc: "#ops", matrix: "ops" }

    - matrix_mattermost_bridges:
       - name: "town-square"
         matrix: "general"
         display_name: "general"
         type: "O"
         header: "Join ~hackday -- it's where sysadmins and friends come to chat"
       - name: "hackday"
         matrix: "hackday"
         display_name: "hackday"
         type: "O"
         header: "SRCF hackery"
       - name: "welcome"
         matrix: "welcome"
         display_name: "welcome"
         type: "O"
         header: "Hello there! Introduce yourself and welcome others :)"
       - name: "society"
         matrix: "society"
         display_name: "society"
         type: "O"
         header: "General society business"
       - name: "executive"
         matrix: "executive"
         display_name: "executive"
         type: "P"
         header: "SRCF Executive"
       - name: "ops"
         matrix: "ops"
         display_name: "ops"
         type: "P"
         header: "SRCF sysadmin chat. Everything is fine."

    - matrix_puppeteer_password_path: /root/matrix-puppeteer-password
    - matrix_registration_secret_path: /root/matrix-registration-secret
    - mattermost_admin_password_path: /root/mattermost-admin-password

  roles:
    - certbot
    - matrix-bridge
