---
- name: Mattermost
  hosts: all
  become: yes
  tags:
    - mattermost
  vars:
    - domain: "mattermost.{{ root_domain }}"
    - certbot_email: soc-srcf-admin@lists.cam.ac.uk
    - mattermost_version: 5.28.1
    - mattermost_checksum: sha256:cb3609c8f7329db9e58655efbec528d666f42cf2d2dfdb22d04ae4964b0eef38
    - mattermost_bbb_plugin_version: 2.1.0
    - mattermost_bbb_plugin_checksum: sha256:2a8b14bb22d44c4039c772b852f5499c1902f3ff6e11eb4dbd583528b5ba3e2e
    - mattermost_admin_password_path: /root/mattermost-admin-password
    - mattermost_public_link_salt_path: /root/mattermost-public-link-salt

    - bbb_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33663363643735663032643066636566653866666338326562643531306230643262666334336364
          3963346164386139656533323434666439663230646332350a316339636331663333363865303830
          65303366666366353066333461326138333732613039396238383862386637663361323235653234
          3036616438656137330a663837336637613562633333653264396166643232666432653233663234
          32633330643630393339656361306662633932613336636166656638366233323037613630376262
          62633466306336626363636532663531666162626361366230316261386366386636383064666137
          35646461303034386336643731653935656534366566396338626264636336386433373634363332
          38363966373865656530

  roles:
    - certbot
    - mattermost

- name: Matrix bridges
  hosts: all
  become: yes
  tags:
    - matrix
  vars:
    - domain: "matrix.{{ root_domain }}"
    - matrix_server_name: "{{ root_domain }}"
    - certbot_email: soc-srcf-admin@lists.cam.ac.uk
    - ubuntu_version: focal
    - keyring_location: /usr/share/keyrings/matrix-org-archive-keyring.gpg
    - matrix_irc_port: 9999
    - matrix_mattermost_port: 9998
    - matrix_mattermost_webhook_port: 9898
    - mattermost_matrixbot_password_path: /root/mattermost-matrixbot-password
    - mattermost_matrixbot_token_path: /root/mattermost-matrixbot-token
    - matrix_irc_bridges:
       - { irc: "#general", matrix: "general" }
       - { irc: "#hackday", matrix: "hackday" }
       - { irc: "#welcome", matrix: "welcome" }
       - { irc: "#society", matrix: "society" }
       - { irc: "#timeout", matrix: "timeout" }
       - { irc: "#executive", matrix: "executive" }
       - { irc: "#ops", matrix: "ops" }

    - matrix_mattermost_bridges:
       - name: "town-square"
         matrix: "general"
         display_name: "general"
         type: "O"
         header: "Join ~hackday -- it's where sysadmins and friends come to chat"
       - name: "hackday"
         matrix: "hackday"
         display_name: "hackday"
         type: "O"
         header: "SRCF hackery"
       - name: "welcome"
         matrix: "welcome"
         display_name: "welcome"
         type: "O"
         header: "Hello there! Introduce yourself and welcome others :)"
       - name: "society"
         matrix: "society"
         display_name: "society"
         type: "O"
         header: "General society business"
       - name: "timeout"
         matrix: "timeout"
         display_name: "timeout"
         type: "O"
         header: "Timeout is growing -- let's make it happen!"
       - name: "executive"
         matrix: "executive"
         display_name: "executive"
         type: "P"
         header: "SRCF Executive"
       - name: "ops"
         matrix: "ops"
         display_name: "ops"
         type: "P"
         header: "SRCF sysadmin chat. Everything is fine."

    - matrix_puppeteer_password_path: /root/matrix-puppeteer-password
    - matrix_registration_secret_path: /root/matrix-registration-secret
    - mattermost_admin_password_path: /root/mattermost-admin-password

  roles:
    - certbot
    - matrix-bridge
