---
- name: restart matrix
  systemd:
    name: matrix-synapse
    state: restarted
    daemon_reload: yes

- name: restart matrix-irc
  systemd:
    name: matrix-irc
    state: restarted
    daemon_reload: yes

- name: restart matrix-mattermost
  systemd:
    name: matrix-mattermost
    state: restarted
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
