- name: Install oidentd
  apt:
    package: oidentd
- name: Enable oidentd
  systemd:
    name: oidentd
    state: started
    enabled: true

- name: Install oidentd config
  copy:
    src: oidentd.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644

- name: Install matrix oidentd config
  copy:
    src: matrix-irc.oidentd.conf
    dest: /home/matrix-irc/.oidentd.conf
    owner: matrix-irc
    group: matrix-irc
    mode: 0644

- name: Allow incoming ident
  ufw:
    rule: allow
    port: auth
    proto: tcp

- name: Forbid outgoing postgres
  ufw:
    rule: deny
    port: postgres
    direction: out
    proto: tcp

- name: Get puppeteer password
  password:
    path: "{{ matrix_puppeteer_password_path }}"
  register: matrix_puppeteer_password
  no_log: true

- name: Create bridged rooms and find room ids
  matrix_room:
    username: puppeteer
    password: "{{ matrix_puppeteer_password.meta }}"
    room_alias: "{{ item.matrix }}"
    join_rule: invite
    history_visibility: joined
    invites:
      - "@appservice-irc:{{ matrix_server_name }}"
    power_levels:
      - ["@appservice-irc:{{ matrix_server_name }}", 100]
  register: "matrix_irc_room_ids"
  loop: "{{ matrix_irc_bridges }}"

- import_tasks: bridge_base.yml
  vars:
    - protocol: irc
    - bridge_url: 'https://github.com/matrix-org/matrix-appservice-irc'
    - bridge_version: '0.34.0'
