- name: Get puppeteer password
  password:
    path: "{{ matrix_puppeteer_password_path }}"
  register: matrix_puppeteer_password
  no_log: true

- name: Join bridged rooms
  matrix_room:
    username: puppeteer
    password: "{{ matrix_puppeteer_password.meta }}"
    room_alias: "{{ item.matrix }}"
    join_rule: "invite"
    invites:
      - "@matterbot:{{ matrix_server_name }}"
    power_levels:
      - ["@matterbot:{{ matrix_server_name }}", 100]
  register: matrix_rooms
  loop: "{{ matrix_mattermost_bridges }}"

- import_tasks: srcf.yml

- name: Get token
  mattermost_token:
    username: matrixbot
    password: "{{ mattermost_matrixbot_password.meta }}"
    token_description: "bridge bot"
    path: "{{ mattermost_matrixbot_token_path }}"
  register: bot_user

- import_tasks: bridge_base.yml
  vars:
    - protocol: mattermost
    - bridge_url: 'https://github.com/dalcde/matrix-appservice-mattermost'
    - bridge_version: e3633ecb587a38578085ef06ffd9e91db7fe4ce1 # v0.1.0
