---
- name: Find mattermost admin user
  become_user: mattermost
  command: "mattermost user search admin"
  changed_when: false
  register: admin_user

- name: Create mattermost admin user if missing
  become_user: mattermost
  command: "mattermost user create --email devnull@srcf.net --system_admin true --username admin --password {{ mattermost_admin_password }}"
  when: '"auth_service" not in admin_user.stdout'

- name: Verify mattermost admin user email
  become_user: mattermost
  command: "mattermost user verify admin"
  when: '"auth_service" not in admin_user.stdout'

- name: Save mattermost admin password
  copy:
    dest: /root/mattermost-admin-password
    content: "{{ mattermost_admin_password }}\n"
