---
- name: Copy mattermost systemd config
  copy:
    src: mattermost.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: restart mattermost

- name: Enable mattermost
  systemd:
    enabled: true
    state: started
    name: mattermost

- name: Copy mattermost nginx config
  template:
    src: mattermost.conf
    dest: /etc/nginx/sites-available/mattermost.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable mattermost nginx config
  file:
    src: /etc/nginx/sites-available/mattermost.conf
    dest: /etc/nginx/sites-enabled/mattermost.conf
    owner: root
    group: root
    state: link
  notify: reload nginx
