---
- name: Copy mattermost systemd config
  copy:
    src: mattermost.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: restart mattermost

- name: Enable mattermost
  systemd:
    enabled: true
    state: started
    name: mattermost

- name: Check if admin token exists
  stat:
    path: /etc/mattermost-admin-token
  register: admin_token

- name: Create internal admin access token
  mattermost_token:
    username: admin
    password: "{{ mattermost_admin_password }}"
    token_description: "Internal server use. DO NOT DELETE."
  register: admin_token_value
  when: not admin_token.stat.exists

- name: Write admin access token
  copy:
    dest: /etc/mattermost-admin-token
    content: "set $access_token {{ admin_token_value.meta.token }};"
    owner: mattermost
    group: www-data
    mode: 0660
  when: admin_token_value.changed

- name: Copy mattermost nginx config
  template:
    src: mattermost.conf
    dest: /etc/nginx/sites-available/mattermost.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Enable mattermost nginx config
  file:
    src: /etc/nginx/sites-available/mattermost.conf
    dest: /etc/nginx/sites-enabled/mattermost.conf
    owner: root
    group: root
    state: link
  notify: reload nginx
