---
- name: Create SRCF team
  become_user: mattermost
  mattermost_team:
    username: admin
    password: "{{ mattermost_admin_password }}"
    name: srcf
    display_name: srcf
    type: O
  register: team_srcf

- name: Delete off-topic channel
  become_user: mattermost
  mattermost_channel:
    username: admin
    password: "{{ mattermost_admin_password }}"
    team_id: "{{ team_srcf.meta.id }}"
    name: off-topic
    state: absent

- name: Create hackday channel
  become_user: mattermost
  mattermost_channel:
    username: admin
    password: "{{ mattermost_admin_password }}"
    team_id: "{{ team_srcf.meta.id }}"
    name: "{{ item.name }}"
    display_name: "{{ item.display_name }}"
    header: "{{ item.header }}"
    type: O
  loop: "{{ mattermost_rooms }}"
