homeserver:
    server_name: '{{ matrix_server_name }}'
    url: 'https://{{ domain }}/'
appservice:
    port: 9995
    hostname: localhost
    schema: http

mattermost_url: http://localhost:8065
mappings:
    {% for entry in matrix_rooms.results | zip(mattermost_channels.results) %}

    - mattermost: "{{ entry[1].meta['id'] }}"
      matrix: "{{ entry[0].meta['room_id'] }}"

    {% endfor %}

matrix_localpart_prefix: 'mm_'
matrix_display_name_template: '[mm] [DISPLAY]'
matrix_bot:
    username: 'matterbot'
    display_name: 'Mattermost Bridge'

mattermost_bot_userid: "{{ bot_user.meta['userid'] }}"
mattermost_bot_access_token: "{{ bot_user.meta['token'] }}"
database:
    type: postgres
    host: /var/run/postgresql
    username: matrix-mattermost
    database: matrix-mattermost
logging: info
ignored_matrix_users:
  - "@puppeteer:{{ matrix_server_name }}"
  - "@appservice-irc:{{ matrix_server_name }}"
mattermost_email_template: 'devnull-[USERNAME]@srcf.net'
