---
- name: restart mattermost
  systemd:
    name: mattermost
    state: restarted
    daemon_reload: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
